name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Usa la versión que necesitas

    - name: Install dependencies
      run: npm install

    - name: Run SonarQube Scanner
      env:
        SONAR_HOST_URL: http://host.docker.internal:9000
        SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
      run: |
        npx sonarqube-scanner \
          -Dsonar.sources=src \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_LOGIN
